### ISSUE TITLE
Support [hash] in spriteFilename when extracting (Feature Request)

### ISSUE THREAD

**Issue by wanecek** [kisenka/svg-sprite-loader#111] opened 2017-05-11 07:39 UTC
To handle caching of the sprite, it would be useful to be able to include a [hash] in the filename of the sprite.

What would it take to implement this? How can I assist?

**Comment by kisenka** [comment] 2017-05-11 09:14
@wanecek it already supported in `svg-sprite-loader@beta` as `[spritehash]`, e.g:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          spriteFilename: '[chunkname].[spritehash].svg'
          // or as a part of query param
          // spriteFilename: '[chunkname].svg?[spritehash]'
        }
      }
    ]
  }
}
```

Please note: in 2.1.0 it will be renamed to `[hash]`

**Comment by kisenka** [comment] 2017-05-11 09:16
Closing this as duplicate of #98

**Closed by kisenka** 2017-05-11 09:16 UTC
Labels: duplicate
