### ISSUE TITLE
Detecting webpack version via require-ing it works wrong in some tricky cases

### ISSUE THREAD

**Issue by huston007** [kisenka/svg-sprite-loader#338] opened 2019-01-24 16:41 UTC
It's a bug relates to #248.

Here svg-sprite-loader tries to detect webpack version by require-ing it:
https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils/get-webpack-version.js#L2

But this doesn't work if by some reason we have different webpack versions. I think it'd most reliable to analyze current webpack instance instead which loader is running on top.

**Comment by kisenka** [comment] 2019-04-27 19:12
Fixed in `svg-sprite-loader@4.1.4`

**Closed by kisenka** 2019-04-27 19:12 UTC

**Comment by LoicUV** [comment] 2019-07-08 16:44
This change breaks [gatsby-plugin-svg-sprite](https://github.com/marcobiedermann/gatsby-plugin-svg-sprite). It works until v4.1.3

Gatsby allows to override webpack config to add loaders such as this one. Although after your change in 4.1.4, the same line breaks with the error `Error: Cannot find module 'webpack/package.json'`

**Comment by DanielaValero** [comment] 2019-07-17 10:40
Hello,

The same error `Error: Cannot find module 'webpack/package.json'` appears in VSCode with this plugin each time one opens a new `js` file. I had the version 4.1.6, downgrading to 4.1.3 made the error disappear.

**Comment by Nettsentrisk** [comment] 2019-08-15 07:46
Getting the same error as @DanielaValero in VS Code while running ESLint with a webpack resolver.

**Comment by martinkadlec0** [comment] 2019-08-15 13:59
I also just run into the same problem in VSCode

**Comment by agigox** [comment] 2019-10-03 14:00
Hi @DanielaValero ,

Please how did you downgrade to 4.1.3, because I cannot find svg-sprite-loader in my package.json I have gatsby project

**Comment by Klutch27** [comment] 2020-02-26 16:26
Same error as @DanielaValero . Currently using `4.2.1`.

**Comment by martinkadlec0** [comment] 2020-02-26 18:10
Yup, the VS Code error unfortunately persist in 4.2.1 which includes #352.

**Comment by Klutch27** [comment] 2020-02-26 19:19
@martinkadlec0 -- appreciate the quick reply!

**Comment by DanielaValero** [comment] 2020-02-27 16:17
Actually that downgrading thing did not really work... I still have the problem, it has been so long that when is fixed I will miss the false negatives from the lintin notifications panel in VS Code, and the import statements...

**Comment by kisenka** [comment] 2020-04-12 14:52
@agigox @Klutch27 @martinkadlec0 @DanielaValero 

Using autodetecting webpack version was very bad idea. I've published alpha version without detecting webpack version, could some of you guys help me with trying it out?

`npm install svg-sprite-loader@drop-webpack-version-detector`

**Comment by TobiDimmel** [comment] 2020-04-17 15:21
@kisenka 
I had this issue with my reproduction repo of #364, which is an Angular CLI project.
I tried your fixed version on a Windows machine and it worked with this repo.

**Comment by kisenka** [comment] 2020-04-26 15:19
Published `svg-sprite-loader@4.2.6` without version detecting, but checking features instead.
