### ISSUE TITLE
[Question/Request] Get sprite string without the root svg element during SSR. Help with easier SSR sprites injection for React.

### ISSUE THREAD

**Issue by aga5tya** [kisenka/svg-sprite-loader#165] opened 2017-07-31 18:16 UTC
**Do you want to request a feature, report a bug or ask a question?**
Question/Feature-Request.

**What is the current behavior?**
The sprite string extracted at SSR contains root svg tag along symbols. This makes it difficult to render when no template strings is being used and instead react components are used at server side render.

**What is the expected behavior?**
There should be an option to extract only the inner string without the root svg tag so dangerouslySetInnerHTML can be leveraged on react svg element.

**If this is a feature request, what is motivation or use case for changing the behavior?**
My webpack config is broken into smaller chunks, and svg loader config is shared between server and client. This make it difficult to inject spriteModule just to achieve custom node sprite injection on SSR approach. Since my webpack is shared, server bundling fails when browser spriteModule is used. When using react, there has to be easier way to inject onto custom mount node. Option config ?

**Please tell us about your environment:**

- Node.js version: 8.2.1
- webpack version: 3.4.1
- svg-sprite-loader version: 3.0.7
- OS type & version: OSX sierra

**Comment by kisenka** [comment] 2017-07-31 22:00
It's possible by invoking `toString()` on each sprite symbol. Just change [this line](https://github.com/kisenka/svg-sprite-loader/blob/e594ade6b40254a914c267761b8be83f6d350adb/examples/server-side-rendering/main.js#L7) to: 
```js
const spriteContent = sprite.symbols.map(s => s.toString()).join('\n');
```

and you will get sprite string without root nodes.

**Comment by aga5tya** [comment] 2017-08-01 07:45
@kisenka, Thanks that works, but now i end up with two svg nodes as below, one from server and one from client. Anyway i can render the icons on server on initial and then browser sprite runtime continues to append further to this?
Or is this already the way and i'm missing on something ?

![screen shot 2017-08-01 at 1 11 54 pm](https://user-images.githubusercontent.com/17351163/28814456-4b3e3648-76bb-11e7-9823-078524eba4b6.png)

**Comment by kisenka** [comment] 2017-08-01 07:58
@aga5tya try to create your own sprite based on [default](https://github.com/kisenka/svg-sprite-loader/blob/e594ade6b40254a914c267761b8be83f6d350adb/runtime/browser-sprite.js):

**my-super-sprite.js**
```js
import BrowserSprite from 'svg-baker-runtime/browser-sprite';

const sprite = new BrowserSprite();

// Sprite DOM node is already there, so we don't need to mount it, 
// just assign existing element to sprite instance
sprite.node = document.querySelector('body svg:first-child');

export default sprite;
```
And setup properly webpack config to use your custom sprite:
**webpack.config.js**
```js
{
  test: /\.svg$/,
    loader: 'svg-sprite-loader',
    issuer: /src\/react-components/, // this rule should be applied only for client side code
    options: {
      spriteModule: './my-super-sprite.js'
    }
}
```

**Comment by aga5tya** [comment] 2017-08-01 08:44
@kisenka: I actually did try that, but couldn't get it work because of the reasons below.

1) The webpack files are pieced and uses 'webpack-config' library similar to the structure below.
  https://github.com/reactql/kit/tree/master/kit/webpack. 
Now the relative path always tries to resolve from the folder where my icons are placed. Absolute full path works fine tho. I think its to do with the way i'm using webpack files at server to compile.

2) But since i have same webpack file with svg loader serving both my server and client bundles, the server build fails in the custom sprite, since it needs browser stuff. I would like not to split my loader config in two parts. Any suggestions around this, it's just to keep things DRY?

Wouldn't it be good that options accept this dom query string if provided and use that as default custom node? This would help in all ssr cases. Let me know your thoughts.

**Comment by aga5tya** [comment] 2017-08-01 08:59
@kisenka, i did as you have suggested by hooking onto webpack config and removing the server side spriteModule config. Now now the symbol's are duplicated

![screen shot 2017-08-01 at 2 25 51 pm](https://user-images.githubusercontent.com/17351163/28817400-ba76d236-76c5-11e7-871a-e5e3bfce3861.png)

**Comment by kisenka** [comment] 2017-08-01 10:19
Seems like it's a bug, because sprite [should replace symbol with the same id](https://github.com/kisenka/svg-baker/blob/88391d4b6b46fa1cf4bedcfd55748ed68c1455cd/packages/svg-baker-runtime/src/sprite.js#L24) (related [test](https://github.com/kisenka/svg-baker/blob/88391d4b6b46fa1cf4bedcfd55748ed68c1455cd/packages/svg-baker-runtime/test/sprite.test.js#L18)). 

@aga5tya could you make a minimal demo repo where I can reproduce described behaviour and dive deep?

**Comment by aga5tya** [comment] 2017-08-01 15:53
@kisenka, will give a repro in few hours. 👍

**Comment by aga5tya** [comment] 2017-08-05 14:17
@kisenka, couldn't revert any earlier, apologies.

I have pushed the repro to below
https://github.com/aga5tya/react-universally/tree/svg-sprite-test
> Commit: https://github.com/aga5tya/react-universally/commit/423c0af375d9207ea775287c968e7c74c0539643

```yarn install and yarn run develop``` will get the app on localhost: 1337, I have included a test icon, and when you examine the ssr server html response there is one symbol in svg root, client side injects the duplicate alongside. Please let me know if you need further info.

**Comment by aga5tya** [comment] 2017-08-13 18:28
@kisenka, I'm still unable to figure out where the issue lies, hope you got a chance to look at the repro i shared. :)

**Comment by kisenka** [comment] 2017-08-13 18:32
@aga5tya thanks for pinging, I am working on it. Actually this issue is duplicate of #8

**Comment by kisenka** [comment] 2017-08-16 06:00
@aga5tya update svg-sprite-loader dependencies, now it's possible to attach the sprite to existing DOM element:

**my-super-sprite**
```js
import BrowserSprite from 'svg-baker-runtime/browser-sprite';

const sprite = new BrowserSprite();

document.addEventListener('DOMContentLoaded', () => {
  sprite.attach( document.querySelector('body svg:first-child') );
});

export default sprite;
```

It will scan for `<symbol>` and reuse them. The rest SVGs added via normal way should works fine with it.

**Comment by aga5tya** [comment] 2017-08-16 11:17
@kisenka Thank You!,, will check it once i get back from work.

**Closed** 2017-08-16 11:45 UTC
Labels: question, wait for reply

**Comment by kisenka** [comment] 2017-08-16 11:47
@aga5tya forget about snippet above, I've added this feature in svg-sprite-loader@3.2.0, it should works out of the box. Please try it.
