### ISSUE TITLE
Image URL mentioned in css files doesn't get converted to SVG URLS in generated css files.

### ISSUE THREAD

**Issue by Temp2017** [kisenka/svg-sprite-loader#133] opened 2017-05-31 09:49 UTC
I mentioned URL in css file as 
background: url("./assets/circle.svg");
 but in converted css file it does not point to svg file generated, instead it points to same path from source
 background: url(C:\Users\gauravgu\Desktop\work\svgspriteloader\assets\circle.svg);
//Expected Behaviour: It should be background: url(sprite.svg#circle-usage);
Please see below configuration and source files.
----------------------------------------------------------------------------
webpack.config.js:
const path = require('path');
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');
const TextExtractPlugin = require('extract-text-webpack-plugin');
const CSSExtractor = new TextExtractPlugin('[name].css');
const HTMLExtractor = new TextExtractPlugin('[name].html');

module.exports = {
    entry: "./index.js",
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: "bundle.js"
    },
    module: {
            rules:[
                {
                    test: /\.svg$/,
                    use: [
                            {
                                loader: 'svg-sprite-loader',
                                options: {
                                extract: true,
                                spriteFilename: 'sprite.svg'
                                }
                            },
                            'svg-fill-loader',
                            'svgo-loader'
                            ]
                },
                  {
                    test: /\.css$/,
                    loader: CSSExtractor.extract({ use: 'css-loader' })
                  },
                  {
                    test: /\.html$/,
                    loader: HTMLExtractor.extract({ use: 'html-loader' })
                  }
            ]
        },
    plugins: [
          CSSExtractor,
    HTMLExtractor,
    new SpriteLoaderPlugin(),

    ],
}
-------------------------
package.json:
{
  "name": "svgspriteloader",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "svg-sprite-loader": "^3.0.2"
  },
  "devDependencies": {
    "extract-text-webpack-plugin": "^2.1.0",
    "svg-fill-loader": "0.0.8",
    "svgo-loader": "^1.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
-----------------------------------------------
index.js
import logo from "./assets/thumbnails.svg";
import circle from "./assets/circle.svg";
import ellipse from "./assets/ellipse.svg";
import './main.css';
----------------------
main.css : 
body {
    background: url("./assets/circle.svg");
}
######################################
sprite.svg is generated properly but content of generated main.css is:
body {
    background: url(C:\Users\gauravgu\Desktop\work\svgspriteloader\assets\circle.svg);
}
=>This URL should be sprite.svg#circle-usage ?

**Comment by Temp2017** [comment] 2017-05-31 10:26
https://gist.github.com/Temp2017/7075932163f3bbd0e6b50d59a307e313

**Comment by kisenka** [comment] 2017-05-31 10:54
@Temp2017 it works in macOS, which Windows version is used?

**Comment by Temp2017** [comment] 2017-05-31 10:55
I am using windows10

**Comment by Temp2017** [comment] 2017-05-31 10:57
Is there some URL loader plugin that we need to use explicitly for converting URL path mentioned in css to point to svg.

**Comment by kisenka** [comment] 2017-05-31 10:58
No, I think it's Windows path resolving issue, I'll check

**Comment by kisenka** [comment] 2017-05-31 11:03
Also I need Node.js version

**Comment by Temp2017** [comment] 2017-05-31 11:06
node version v6.10.0

**Comment by kisenka** [comment] 2017-05-31 15:54
Please check `svg-sprite-loader@3.0.4`

**Closed** 2017-05-31 15:53 UTC

**Comment by asimonok** [comment] 2017-06-01 10:50
@kisenka I also encountered such a problem on Mac. Adding in id '-usage'
Node v6.10.3
Svg-sprite-loader v3.0.4

**Comment by kisenka** [comment] 2017-06-01 10:52
@asimonok please provide a project that I can `npm install` and `npm start` and then follow README.md to reproduce.

**Comment by asimonok** [comment] 2017-06-01 11:02
@kisenka I don't provide project. Here is configuration in my webpack.config.js
const SpritePlugin = require('svg-sprite-loader/plugin')

const spriteLoader = JSON.stringify({
  symbolId: '[name]',
  extract: true,
  spriteFilename: `icons.[${project.compiler_hash_type}].svg`,
})

loaders: [{
  test: /\.svg$/,
  include: project.paths.client('icons'),
  loaders: [
  `svg-sprite-loader?${spriteLoader}`,
  `svgo-loader?${svgoLoader}`,
  ],
}]

plugins: [
  new SpritePlugin(),
]

Maybe is it because of the use 'svgo-loader'?

**Comment by kisenka** [comment] 2017-06-01 11:13
@asimonok I need whole loaders configuration and piece of your code which produces described issue

**Comment by Eireen** [comment] 2017-06-01 23:40
Same problem on Xubuntu 12.04, Node.js v7.10.0.

I found that if a source CSS file contains more than one occurrence of the same icon, only the first occurrence is processed properly.

The example of source:

```css
.a { background-image: url(../images/arrow_up_green.svg); }
.a { background-image: url(../images/arrow_up_green.svg); }
.a { background-image: url(../images/arrow_up_green.svg); }
```

The result:

```css
.a { background-image: url(sprite.svg#arrow_up_green-usage); }
.a { background-image: url(/home/eireen/projects/gs/src/images/arrow_up_green.svg); }
.a { background-image: url(/home/eireen/projects/gs/src/images/arrow_up_green.svg); }
```

My [webpack.config.js](https://gist.github.com/Eireen/b235013758311ceb79e7d8016a231bd3)

**Comment by Temp2017** [comment] 2017-06-02 05:12
@kisenka 
Yes, same issue on Mac too,
I checked your changes to resolve this issue on Window, which contains some windows specific flag, seems this needs to be generic on all platform.

**Comment by kisenka** [comment] 2017-06-02 07:46
Sorry guys, please check `svg-sprite-loader@3.0.5`, that should be fixed. I've also add corresponding [test](https://github.com/kisenka/svg-sprite-loader/blob/0640a40211c7bbbc3845f3a94f3698a82c2bf6fd/test/loader.test.js#L126).

**Comment by Eireen** [comment] 2017-06-02 16:08
It works. Thanks a lot!

**Comment by Eireen** [comment] 2017-06-02 18:10
The problem seems to come back after I added the 'svg-fill-loader' plugin :)

```css
.a { background-image: url(../images/icn_search.svg?fill=#0e334f); }
```

turns into

```css
.a { background-image: url(/home/eireen/projects/gs/src/images/icn_search.svg#0e334f); }
```
