### ISSUE TITLE
Error: "request.includes is not a function"

### ISSUE THREAD

**Issue by Venryx** [kisenka/svg-sprite-loader#115] opened 2017-05-12 11:07 UTC
I'm getting the following error when attempting to use this plugin:
```
C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils.js:168
if (request && (!request.includes(spriteLoaderPath) || !rule)) {
                           ^

TypeError: request.includes is not a function
    at isModuleShouldBeExtracted (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils.js:168:28)
    at Array.filter (native)
    at Object.aggregate (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils.js:286:30)
    at Compilation.replacePlaceholdersInModules (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\plugin.js:35:27)
    at Compilation.applyPlugins1 (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:14)
    at Compilation.seal (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:573:8)
    at C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compiler.js:488:16
    at C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:477:11)
    at processModuleDependencies.err (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:448:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```

Here is my config: (well, the relevant part, as it is quite large)
```
const SpriteLoaderPlugin = require("svg-sprite-loader/plugin");
webpackConfig.plugins.push(
	new SpriteLoaderPlugin()
);
webpackConfig.module.rules.push({
	test: /\.svg$/,
	use: [
		"svg-sprite-loader",
		"svgo-loader",
	]
});
```

I'm using:
* Webpack: 2.4.1
* svg-sprite-loader: 2.0.5

**Comment by kisenka** [comment] 2017-05-12 11:08
@Venryx which node.js version used?

**Comment by Venryx** [comment] 2017-05-12 11:17
Node.js 6.9.1

**Comment by kisenka** [comment] 2017-05-12 11:18
Try beta version please - `npm install svg-sprite-loader@beta`

**Comment by Venryx** [comment] 2017-05-12 11:22
Same issue:
```
C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils\is-module-should-be-extracted.js:25
  if (request && (!request.includes(spriteLoaderPath) || !rule)) {
                           ^

TypeError: request.includes is not a function
    at isModuleShouldBeExtracted (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils\is-module-should-be-extracted.js:25:28)
    at Array.filter (native)
    at new MappedList (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\utils\mapped-list.js:45:42)
    at Compilation.replacePlaceholdersInModules (C:\Root\Apps\@V\DebateMap\Main\node_modules\svg-sprite-loader\lib\plugin.js:36:21)
    at Compilation.applyPlugins1 (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:14)
    at Compilation.seal (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:573:8)
    at C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compiler.js:488:16
    at C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:477:11)
    at processModuleDependencies.err (C:\Root\Apps\@V\DebateMap\Main\node_modules\webpack\lib\Compilation.js:448:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

By the way, if I add this line: (just before the line that fails)
```
 console.log("Type:" + typeof request);
```

I get:
```
Type: undefined
Type: string
```

**Comment by kisenka** [comment] 2017-05-12 11:23
Ok, I need demo repo with your setup

**Comment by Venryx** [comment] 2017-05-12 11:23
Okay. I'll work it at some more myself, and see if I can solve it; if not, I'll try to get a demo repo set up.

**Comment by kisenka** [comment] 2017-05-12 13:45
I am still asking you to create repo with reproducible behaviour - it will helps to detect errors and fix them.

**Comment by psachs21** [comment] 2017-05-23 17:24
@kisenka I've reproduced this issue with this simple repo: https://github.com/psachs21/web-boilerplate.

To reproduce:
- install (npm or yarn)
- run `build:vendor`
- run `build`

The issue seems to be caused by having a DLL reference plugin. Might be other causes but this is the one i found.

**Comment by kisenka** [comment] 2017-05-24 11:08
@psachs21 getting following error: 

```
@fss/react-components' is not in the npm registry
```

**Comment by steplov** [comment] 2017-05-24 11:23
Hello,

I have the same problem and can confirm this problem appears with DLL reference plugin.

**Comment by kisenka** [comment] 2017-05-24 12:24
@steplov could you please create demo repo with minimal setup: package.json, webpack.config.js and minimal code which reproduce the problem?

**Comment by steplov** [comment] 2017-05-24 13:28
@kisenka sure, i will add it in the evening

**Comment by kisenka** [comment] 2017-05-24 13:57
@steplov @Venryx @psachs21 fixed in `svg-sprite-loader@3.0.2`, please check

**Comment by psachs21** [comment] 2017-05-24 14:41
@kisenka apologies for forgetting about the private repo, was trying to extract the basics. Anyways, 3.0.2 resolves everything!

**Comment by kisenka** [comment] 2017-05-24 14:42
@psachs21 thanks for the participation!

**Comment by psachs21** [comment] 2017-05-24 17:51
@kisenka So it works but it turns out that the extract isn't working in this case though. If the svg file is in the DLL, nothing is extracted even in extract mode.

**Comment by steplov** [comment] 2017-05-24 22:06
@kisenka, @psachs21  Hi, I added 2 examples with dll plugin here https://github.com/steplov/svg-sprite-loader/tree/webpack-dll-plugin . As Paul said before, it isn't working if 'extract' option was passed. I can take a look if you want

**Comment by steplov** [comment] 2017-05-25 10:24
I re-checked examples and now it works properly. Also i added a pull request with a this changes. So i think issue is solved

**Comment by psachs21** [comment] 2017-05-25 14:46
I'll test my example again but i could have sworn it was not working. Although my example has the SVG sitting in node_modules as a dep, so it might be slightly different.

**Comment by psachs21** [comment] 2017-05-25 14:50
Ah, nevermind. Everything seems to be working now. Not sure why it wasn't before. All is well!

**Closed** 2017-05-26 06:19 UTC
Labels: wait for reply
